/*fix test session*/
UPDATE TESTSESSION SET PROJECT_ID = (SELECT ID FROM PROJECT);

/*fix analyst patients*/
UPDATE ANALYSTPATIENT SET PROJECT_ID = (SELECT ID FROM PROJECT);

/*add default project to all users*/
INSERT INTO USER_PROJECT SELECT USER.id, PROJECT.id FROM USER, PROJECT;